# Wazuh App Copyright (C) 2020 Wazuh Inc. (License GPLv2)
version: '3'

services:
  wazuh_master:
    image: wazuh/wazuh:3.12.2_7.6.2
    hostname: wazuh_master
    restart: always
    environment:
      - CLUSTER_KEY=d1df710bdf0f2b3b2be9ea15be8f0ea8
    volumes:
      - "./wazuh-worker/etc:/wazuh-config-mount/etc"
      - "./wazuh-worker/02-config_cluster.sh:/entrypoint-scripts/02-config_cluster.sh"
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    deploy:
      mode: global

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.12.2_7.6.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 4g

  kibana:
    image: wazuh/wazuh-kibana:3.12.2_7.6.2
    hostname: kibana
    restart: always
    environment:
      - "WAZUH_API_URL=https://wazuh_master"
    depends_on:
      - elasticsearch

  nginx:
    image: wazuh/wazuh-nginx:3.12.2_7.6.2
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana

  wazuh_loadbalancer:
    image: wazuh-loadbalancer
    restart: always
    environment:
      - NGINX_PORT=443
    depends_on:
      - wazuh_worker

  wazuh_worker:
    image: wazuh/wazuh:3.12.2_7.6.2
    restart: always
    environment:
      - CLUSTER_KEY=d1df710bdf0f2b3b2be9ea15be8f0ea8
    volumes:
      - "./wazuh-worker/etc:/wazuh-config-mount/etc"
      - "./wazuh-worker/02-config_cluster.sh:/entrypoint-scripts/02-config_cluster.sh"
    depends_on:
      - wazuh_master
    deploy:
      replicas: 2

  agent:
    image: wazuh-agent
    restart: always
    environment:
      - QUEUE_SIZE=10000 #max 100.000
      - EVENTS_PER_SECOND=1000 #max 1000
    depends_on:
      - loadbalancer
    deploy:
      replicas: 10
